### ISSUE TITLE
Needs gist describing writing portion.

### ISSUE THREAD

**Issue by pemj** [pemj/MayaPy#1]
For the deformers listed here:
1. blend shapes
2. cluster deformers
3. texture deformers
4. wire deformers
5. wrap (and lattice) deformers
6. muscle deformers
7. point on curve deformers
8. influence objects

We need to consider and describe:
1. What are the advantages/disadvantages of each? (When use one deformer over another?)
2. There is benefit in using them in combination (e.g., in series and parallel, or globally versus
locally, etc.). How does one combine them and get them to ‘play nice’?
3. What are the ‘best practices’ used by the facial animation community for using deformers to
model faces and expressions?

**Comment by ryeleo** [comment]
This will be totally overkill for this particular project, but it looks like it'll be a really good survey for learning deformers. Nice.

**Comment by pemj** [comment]
Well, may or may not be overkill for the project, but, it's also assignment 5.

[assignment 5.pdf](https://github.com/pemj/MayaPy/files/35086/assignment.5.pdf)

**Comment by pemj** [comment]
Closed, pending review of materials for project criteria fulfillment.
