### ISSUE TITLE
Use lattice deformer for head eccentricity 

### ISSUE THREAD

**Issue by ryeleo** [pemj/MayaPy#10]
Currently the only way I have tried to do head eccentricity is by hacking the 'outer vertecies of the model and making the face appear wider, wanna try instead actually using a lattice deformer and counteracting its effect on the front of the face by using either an inner-lattice deformer or cluster deformer.

**Comment by pemj** [comment]
Have not tried this.  Was on a roll, so did the soft select hack while I was at it.

**Comment by ryeleo** [comment]
I agree, the end result we have now looks good -- if we have more time we can play with a solution like this, but current solution looks completely sufficient.
