### ISSUE TITLE
Redo facial animations

### ISSUE THREAD

**Issue by ryeleo** [pemj/MayaPy#11]
Once I have completed the "2.0" version of the model, we will need to redo all of the animations.

**Comment by pemj** [comment]
Took charge of this issue.
Mouth size/shape animations: looking good.
eyebrow animations: looking good
eye size animation: looking good
horizontal eye distance, head eccentricity: next up

**Comment by pemj** [comment]
horizontal eye distance and head eccentricity looking good.

**Comment by pemj** [comment]
mouth animations seem to play nicely now.
