### ISSUE TITLE
Maximizing is a little wonky

### ISSUE THREAD

**Issue by pemj** [pemj/MayaPy#13]
When the eye-size and eye-width are both maximized, eyebrows start clipping unpleasantly, and the edges of the eye sockets get a little unpleasant.

We'll need to fix the deformers to make them stack a little easier.

This is a slight issue in the mouth region, but it seems to have been largely ameliorated by scaling down the maximum deformation a bit.

**Comment by ryeleo** [comment]
Did my best to fix up all of these in the "beautifying" branch that I will make a pull request for now.
