### ISSUE TITLE
"Clicking" the QT sliders does not adjust the deformers

### ISSUE THREAD

**Issue by ryeleo** [pemj/MayaPy#14]
If the user clicks on the bar instead of click-dragging the knob, then the deformers do not get adjusted.

**Comment by pemj** [comment]
Yeah, there are some peculiarities there.  If you make the deformers trigger whenever the slider is changed, it changes the face once for every value you move past, which results in some laggy and ugly behavior.

**Comment by ryeleo** [comment]
I'm unsure how it performs on other machines, but I found that behavior (laggy & ugly) preferable to the need to click on the button behavior. Might need to see the behavior on a less performant machine.

Will implement the solution mentioned by moderator on this forum.
https://forum.qt.io/topic/22609/qslider-needs-to-step-with-custom-step-value-on-mouse-slide/4
