### ISSUE TITLE
Add demo examples

### ISSUE THREAD

**Issue by pemj** [pemj/MayaPy#3]
Let's mock up some of the stuff we'll be doing with blend shapes, wire deformers, and cluster deformers.  Get some photos, maybe a short video that we can stick on a drive and bring into class to show off some of the more dynamic bits and pieces, if we're feeling ambitious and we've got leftover time between other assignments.

**Comment by ryeleo** [comment]
Sounds good, I will throw together demos for blend shape, cluster deformer, and texture deformer when I get home. Will contact later this evening to make sure we don’t duplicate demo-creation efforts.

Ryan Leonard
ryan.leonard71@gmail.com
