### ISSUE TITLE
Peter and Ryan, could you please save the current .ma file as a zip?

### ISSUE THREAD

**Issue by Kentrosaurus** [pemj/MayaPy#6]
HI.  I find that if I download any .ma files they are not openable in Maya.  Could you please place a zipped version of your .ma in your repo?  Thanks.

Kent

**Comment by pemj** [comment]
Just got this email.  Zipped version?  I'll give it a shot real quick,
still have a bike ride between here and class, and I think Ryan is holding
office hours or something.

**Comment by Kentrosaurus** [comment]
n.p.  We can do it in class too.

Kent
